# Generated by Django 4.0.5 on 2022-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('FeMale', 'Female')], default='Male', max_length=6)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Number_Of_Adult', models.IntegerField()),
                ('Number_of_Children', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guest_count', models.IntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('types', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('availability', models.BooleanField(default=True)),
                ('About', models.CharField(max_length=500)),
            ],
        ),
    ]
